### ISSUE TITLE
Problem running addon in both Ubuntu and Windows

### ISSUE THREAD

**Issue by DLDrago** [MinshuG/BlenderUmap2#3]
![image](https://user-images.githubusercontent.com/8620641/219214848-447e18cb-093c-4201-bccf-9c21c2066a4f.png)
I get this error when I try to use the addon.  It doesn't matter what operating system I use, I get this exact error.  Picture taken in Ubuntu.

**Comment by MinshuG** [comment]
check Blender's system console https://docs.blender.org/manual/en/2.79/advanced/command_line/introduction.html#linux and share the error

**Comment by DLDrago** [comment]
```dldrago@dldrago-X170KM-G:~/.config/blender/3.4/scripts/addons/BlenderUmap$ blender
Read prefs: /home/dldrago/.config/blender/3.4/config/userpref.blend
[18:53:09 INF] Reading config file /media/dldrago/External SSD/Models/FF7PS4/Umap2/config.json
[18:53:09 INF] Pak "pakchunk3_s12-ps4.pak": 56 files, mount point: "End/Content/GameContents/Environment/", version 4 in 00:00:00.0049592
...
[18:53:10 WRN] Object 140-SBIL0_Layout__CMPNY_010-Outside.140-SBIL0_Layout__CMPNY_010-Outside not found
Traceback (most recent call last):
  File "/home/dldrago/.config/blender/3.4/scripts/addons/BlenderUmap/main.py", line 386, in execute
    main(context)
  File "/home/dldrago/.config/blender/3.4/scripts/addons/BlenderUmap/main.py", line 51, in main
    subprocess.run(
  File "/snap/blender/3132/3.4/python/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[]' returned non-zero exit status 1.
Error: Python: Traceback (most recent call last):
  File "/home/dldrago/.config/blender/3.4/scripts/addons/BlenderUmap/main.py", line 386, in execute
    main(context)
  File "/home/dldrago/.config/blender/3.4/scripts/addons/BlenderUmap/main.py", line 51, in main
    subprocess.run(
  File "/snap/blender/3132/3.4/python/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[]' returned non-zero exit status 1.```

**Comment by MinshuG** [comment]
1. it's only mounting 56 files. Did you provide correct AES key/s? And have all paks?
2. It can't find the specified umap. Probably because of 1st point.
3. what fortnite code? (Replay reader?)

**Comment by DLDrago** [comment]
For the first one, I left out the part where it loaded more.  Didn't want to clog the log with lots of pak loading.
As for the Fortnite code, it's the replay stuff.  I'm rebuilding it with the code intact to see if that fixes it.

**Comment by MinshuG** [comment]
why is your umap path just `140-SBIL0_Layout__CMPNY_010-Outside.140-SBIL0_Layout__CMPNY_010-Outside` use full path

**Comment by DLDrago** [comment]
For the first one, I left out the part where it loaded more.  Didn't want to clog the log with lots of pak loading.
As for the Fortnite code, it's the replay stuff.  I'm rebuilding it with the code intact to see if that fixes it.

**Comment by DLDrago** [comment]
While you're working on it, you might want to look at this:
```
/home/dldrago/Downloads/BlenderUmap2/BlenderUmap.sln : Solution file error MSB5004: The solution file has two projects named "CUE4Parse-Conversion".
    0 Warning(s)
    1 Error(s)
```

**Comment by MinshuG** [comment]
> why is your umap path just `140-SBIL0_Layout__CMPNY_010-Outside.140-SBIL0_Layout__CMPNY_010-Outside` use full path

**Comment by DLDrago** [comment]
The usage instructions aren't very clear.

**Comment by DLDrago** [comment]
New build problem:
```/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/Extensions/ReplayExporter.cs(63,29): error CS1061: 'ReplayReader' does not contain a definition for 'Builder' and no accessible extension method 'Builder' accepting a first argument of type 'ReplayReader' could be found (are you missing a using directive or an assembly reference?) [/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/BlenderUmap.csproj]
/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/Extensions/ReplayExporter.cs(93,65): error CS1061: 'UStaticMeshComponent' does not contain a definition for 'GetStaticMesh' and no accessible extension method 'GetStaticMesh' accepting a first argument of type 'UStaticMeshComponent' could be found (are you missing a using directive or an assembly reference?) [/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/BlenderUmap.csproj]
/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/Extensions/ReplayExporter.cs(99,69): error CS1061: 'UStaticMeshComponent' does not contain a definition for 'GetStaticMesh' and no accessible extension method 'GetStaticMesh' accepting a first argument of type 'UStaticMeshComponent' could be found (are you missing a using directive or an assembly reference?) [/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/BlenderUmap.csproj]
/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/BlenderUmap.cs(558,44): error CS1729: 'MeshExporter' does not contain a constructor that takes 3 arguments [/home/dldrago/Downloads/BlenderUmap2/BlenderUmap/BlenderUmap.csproj]```

**Comment by MinshuG** [comment]
pull latest cue4parse

**Comment by DLDrago** [comment]
> pull latest cue4parse

How do I do that?  I tried "git pull" and it said "Already up to date."

**Comment by DLDrago** [comment]
I guess the main issue was that I was trying to build the addon on Linux instead of Windows.  It works now.
