### ISSUE TITLE
Cannot open PC versions of FF7 Remake Intergrade Maps

### ISSUE THREAD

**Issue by DLDrago** [MinshuG/BlenderUmap2#5]
I have this error from the Blender console:

```
[18:05:27 ERR] Failed to load package End/Content/GameContents/Level/Game/Field/010-MAKO1/Layout_Merge/010-MAKO1_Layout_010-Station.umap
CUE4Parse.UE4.Exceptions.ParserException: Package has unversioned properties but mapping file is missing, can't serialize
   at CUE4Parse.UE4.Assets.Package..ctor(FArchive uasset, FArchive uexp, Lazy`1 ubulk, Lazy`1 uptnl, IFileProvider provider, TypeMappings mappings, Boolean useLazySerialization)
   at CUE4Parse.FileProvider.AbstractFileProvider.TryLoadPackageAsync(GameFile file)
```

**Comment by DLDrago** [comment]
Here's the full log:
[BlenderUmap-2023-03-13.log](https://github.com/MinshuG/BlenderUmap2/files/10962302/BlenderUmap-2023-03-13.log)

**Comment by MinshuG** [comment]
Missing mappings. Get it from here https://github.com/OutTheShade/Unreal-Mappings-Archive/tree/main/CCFF7R
